# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
misc {
  vrr = 0
}

general {
  allow_tearing = false
}

input {
  touchpad {
    scroll_factor = 1.0
  }
}
