# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

windowrulev2 = opacity 0.89 override 0.89 override, class:.*
windowrulev2 = noblur, xwayland:1

# Float Dolphin
windowrulev2 = float, class:^(org\.kde\.dolphin)$
windowrulev2 = size 65%, class:^(org\.kde\.dolphin)$
